# Generated by Django 4.1 on 2023-03-24 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partida',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
